### ISSUE TITLE
[ttyc 11:28:29] handshake failed (unable to connect or wrong user/pass): Get "http://my.server/ttyd/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by rihaq** [Depau/ttyc#1]

**Comment by rihaq** [comment]
[ttyc 11:35:35] handshake failed (unable to connect or wrong user/pass): unexpected end of JSON input

**Comment by Depau** [comment]
Fixed with latest release, I can't believe I had HTTP basic auth broken all of this time.

Thanks for reporting

**Comment by rihaq** [comment]
`[ttyc 13:39:33] unable to connect or authenticate to server: failed to WebSocket dial: expected handshake response status code 101 but got 401` 
Still not fixed brother
